Universidad Torcuato Di Tella

Licenciatura en Tecnología Digital\
**Tecnología Digital VI: Inteligencia Artificial**

# **XGBoost**

En esta *notebook*, crearemos un modelo usando XGBoost, para tratar de predecir decisiones bancarias de clientes.

XGBoost viene de eXtreme Gradient Boosting y es una librería de árboles de decisión impulsados por gradiente.

XGBoost se importa usando el paquete `xgboost` y se suele usar el alias `xgb`.

In [1]:
# !pip install -U xgboost

import xgboost as xgb

ModuleNotFoundError: No module named 'xgboost'

También importamos otras utilidades necesarias:

In [ ]:
import pandas as pd # Para cargar los datos y hacer OHE.
import numpy as np  # Para lidiar con NaNs.
import time
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import balanced_accuracy_score, roc_auc_score, make_scorer
from sklearn.model_selection import ParameterSampler
from sklearn.metrics import confusion_matrix

random_state = 42
np.random.seed(random_state)

### **Carga del *data frame***

Cargamos un archivo CSV que tiene datos bancarios y una variable predictora yes/no que es la columna `y` e indica si el cliente se suscribió o no a un depósito a plazo. Fuente: https://archive.ics.uci.edu/dataset/222/bank+marketing. Ya está disponible en el Campus Virtual, en la sección `Datasets`.

In [ ]:
df = pd.read_csv('./bank-full.csv', sep = ';')

In [ ]:
len(df)

45211

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

Miramos las columnas numéricas:

In [ ]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

Miramos las columnas tipo `object` (en este caso, son todas categóricas, encodeadas como *strings*):

In [ ]:
df.describe(include = 'object')

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,45211,45211,45211,45211,45211,45211,45211,45211,45211,45211
unique,12,3,4,2,2,2,3,12,4,2
top,blue-collar,married,secondary,no,yes,no,cellular,may,unknown,no
freq,9732,27214,23202,44396,25130,37967,29285,13766,36959,39922

Investigamos los tipos de cada columna:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

### **Valores faltantes**

XGBoost puede trabajar con valores faltantes. Agregamos algunos en el data frame para demostrarlo.

In [ ]:
probability = 0.2
mask = np.random.rand(*df.shape) < probability
# Removemos el ruido de la columna 'y', ya que no queremos agregar datos faltantes en la variable predictora.
mask[:, mask.shape[1] - 1] = False
df[mask] = np.nan

Podemos observar los datos faltantes como valores NaN:

In [ ]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58.0,management,married,tertiary,NaN,NaN,NaN,no,unknown,5.0,NaN,261.0,1.0,-1.0,NaN,NaN,no
1,44.0,technician,single,secondary,NaN,29.0,yes,no,unknown,NaN,may,151.0,NaN,-1.0,NaN,NaN,no
2,33.0,entrepreneur,married,NaN,no,2.0,NaN,yes,NaN,5.0,may,76.0,1.0,-1.0,0.0,NaN,no
3,47.0,blue-collar,married,unknown,no,NaN,NaN,NaN,unknown,5.0,may,92.0,1.0,-1.0,0.0,NaN,no
4,NaN,unknown,single,NaN,NaN,1.0,no,no,unknown,NaN,may,NaN,1.0,-1.0,0.0,NaN,no

XGBoost no solía soportar variables categóricas, pero actualmente las soporta de forma experimental (fuente: https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html).
        
Sin embargo, en este caso, usaremos one-hot encoding.

In [ ]:
# Importante: ¡sólo poner las categóricas y excluir la variable a predecir!
pd_ohe = pd.get_dummies(df,
                        columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome'],
                        sparse = True,    # Devolver una matriz rala.
                        dummy_na = False, # No agregar columna para NaNs.
                        dtype = int       # XGBoost no trabaja con 'object'; necesitamos que sean numéricos.
                       )
pd_ohe

,age,balance,day,duration,campaign,pdays,previous,y,job_admin.,job_blue-collar,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,58.0,NaN,5.0,261.0,1.0,-1.0,NaN,no,0,0,...,0,0,0,0,0,0,0,0,0,0
1,44.0,29.0,NaN,151.0,NaN,-1.0,NaN,no,0,0,...,0,0,1,0,0,0,0,0,0,0
2,33.0,2.0,5.0,76.0,1.0,-1.0,0.0,no,0,0,...,0,0,1,0,0,0,0,0,0,0
3,47.0,NaN,5.0,92.0,1.0,-1.0,0.0,no,0,1,...,0,0,1,0,0,0,0,0,0,0
4,NaN,1.0,NaN,NaN,1.0,-1.0,0.0,no,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51.0,825.0,17.0,977.0,NaN,NaN,NaN,yes,0,0,...,0,0,0,1,0,0,0,0,0,0
45207,71.0,1729.0,17.0,456.0,NaN,-1.0,0.0,yes,0,0,...,0,0,0,1,0,0,0,0,0,1
45208,72.0,5715.0,17.0,1127.0,5.0,184.0,3.0,yes,0,0,...,0,0,0,1,0,0,0,0,1,0
45209,57.0,668.0,17.0,508.0,4.0,-1.0,0.0,no,0,1,...,0,0,0,1,0,0,0,0,0,1
45210,37.0,2971.0,17.0,361.0,NaN,188.0,11.0,no,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
len(pd_ohe.columns)

52

In [ ]:
pd_ohe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 52 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  36174 non-null  float64
 1   balance              36059 non-null  float64
 2   day                  36255 non-null  float64
 3   duration             36225 non-null  float64
 4   campaign             36270 non-null  float64
 5   pdays                36255 non-null  float64
 6   previous             36170 non-null  float64
 7   y                    45211 non-null  object
 8   job_admin.           45211 non-null  Sparse[int64, 0]
 9   job_blue-collar      45211 non-null  Sparse[int64, 0]
 10  job_entrepreneur     45211 non-null  Sparse[int64, 0]
 11  job_housemaid        45211 non-null  Sparse[int64, 0]
 12  job_management       45211 non-null  Sparse[int64, 0]
 13  job_retired          45211 non-null  Sparse[int64, 0]
 14  job_self-employed    45211 non-null  Sparse[int64, 0]
 15  job_services         45211 non-null  Sparse[int64, 0]
 16  job_student          45211 non-null  Sparse[int64, 0]
 17  job_technician       45211 non-null  Sparse[int64, 0]
 18  job_unemployed       45211 non-null  Sparse[int64, 0]
 19  job_unknown          45211 non-null  Sparse[int64, 0]
 20  marital_divorced     45211 non-null  Sparse[int64, 0]
 21  marital_married      45211 non-null  Sparse[int64, 0]
 22  marital_single       45211 non-null  Sparse[int64, 0]
 23  education_primary    45211 non-null  Sparse[int64, 0]
 24  education_secondary  45211 non-null  Sparse[int64, 0]
 25  education_tertiary   45211 non-null  Sparse[int64, 0]
 26  education_unknown    45211 non-null  Sparse[int64, 0]
 27  default_no           45211 non-null  Sparse[int64, 0]
 28  default_yes          45211 non-null  Sparse[int64, 0]
 29  housing_no           45211 non-null  Sparse[int64, 0]
 30  housing_yes          45211 non-null  Sparse[int64, 0]
 31  loan_no              45211 non-null  Sparse[int64, 0]
 32  loan_yes             45211 non-null  Sparse[int64, 0]
 33  contact_cellular     45211 non-null  Sparse[int64, 0]
 34  contact_telephone    45211 non-null  Sparse[int64, 0]
 35  contact_unknown      45211 non-null  Sparse[int64, 0]
 36  month_apr            45211 non-null  Sparse[int64, 0]
 37  month_aug            45211 non-null  Sparse[int64, 0]
 38  month_dec            45211 non-null  Sparse[int64, 0]
 39  month_feb            45211 non-null  Sparse[int64, 0]
 40  month_jan            45211 non-null  Sparse[int64, 0]
 41  month_jul            45211 non-null  Sparse[int64, 0]
 42  month_jun            45211 non-null  Sparse[int64, 0]
 43  month_mar            45211 non-null  Sparse[int64, 0]
 44  month_may            45211 non-null  Sparse[int64, 0]
 45  month_nov            45211 non-null  Sparse[int64, 0]
 46  month_oct            45211 non-null  Sparse[int64, 0]
 47  month_sep            45211 non-null  Sparse[int64, 0]
 48  poutcome_failure     45211 non-null  Sparse[int64, 0]
 49  poutcome_other       45211 non-null  Sparse[int64, 0]
 50  poutcome_success     45211 non-null  Sparse[int64, 0]
 51  poutcome_unknown     45211 non-null  Sparse[int64, 0]
dtypes: Sparse[int64, 0](44), float64(7), object(1)
memory usage: 6.5+ MB

Comparación con matriz no rala:

In [ ]:
pd.get_dummies(df,
               columns = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome'],
               sparse = False,   # Devolver una matriz densa.
               dummy_na = False, # No agregar columna para NaNs.
               dtype = int       # XGBoost no trabaja con 'object'; necesitamos que sean numéricos.
              ).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 52 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  36174 non-null  float64
 1   balance              36059 non-null  float64
 2   day                  36255 non-null  float64
 3   duration             36225 non-null  float64
 4   campaign             36270 non-null  float64
 5   pdays                36255 non-null  float64
 6   previous             36170 non-null  float64
 7   y                    45211 non-null  object
 8   job_admin.           45211 non-null  int64
 9   job_blue-collar      45211 non-null  int64
 10  job_entrepreneur     45211 non-null  int64
 11  job_housemaid        45211 non-null  int64
 12  job_management       45211 non-null  int64
 13  job_retired          45211 non-null  int64
 14  job_self-employed    45211 non-null  int64
 15  job_services         45211 non-null  int64
 16  job_student          45211 non-null  int64
 17  job_technician       45211 non-null  int64
 18  job_unemployed       45211 non-null  int64
 19  job_unknown          45211 non-null  int64
 20  marital_divorced     45211 non-null  int64
 21  marital_married      45211 non-null  int64
 22  marital_single       45211 non-null  int64
 23  education_primary    45211 non-null  int64
 24  education_secondary  45211 non-null  int64
 25  education_tertiary   45211 non-null  int64
 26  education_unknown    45211 non-null  int64
 27  default_no           45211 non-null  int64
 28  default_yes          45211 non-null  int64
 29  housing_no           45211 non-null  int64
 30  housing_yes          45211 non-null  int64
 31  loan_no              45211 non-null  int64
 32  loan_yes             45211 non-null  int64
 33  contact_cellular     45211 non-null  int64
 34  contact_telephone    45211 non-null  int64
 35  contact_unknown      45211 non-null  int64
 36  month_apr            45211 non-null  int64
 37  month_aug            45211 non-null  int64
 38  month_dec            45211 non-null  int64
 39  month_feb            45211 non-null  int64
 40  month_jan            45211 non-null  int64
 41  month_jul            45211 non-null  int64
 42  month_jun            45211 non-null  int64
 43  month_mar            45211 non-null  int64
 44  month_may            45211 non-null  int64
 45  month_nov            45211 non-null  int64
 46  month_oct            45211 non-null  int64
 47  month_sep            45211 non-null  int64
 48  poutcome_failure     45211 non-null  int64
 49  poutcome_other       45211 non-null  int64
 50  poutcome_success     45211 non-null  int64
 51  poutcome_unknown     45211 non-null  int64
dtypes: float64(7), int64(44), object(1)
memory usage: 17.9+ MB

6 MB vs. 18 MB, aproximadamente.

### **Preparar conjuntos de entrenamiento, validación (*hold-out*) y evaluación**

Para este ejemplo, usaremos conjuntos de datos de *train*, *validation* y *test* fijos. Es decir, para validación usaremos un hold-out *set*. Decidimos esto porque usar *cross-validation* es más costoso.

In [ ]:
y = pd_ohe[['y']].copy() # Usamos copy para no modificar un view abajo, ya que genera un warning.
y

         y
0       no
1       no
2       no
3       no
4       no
...    ...
45206  yes
45207  yes
45208  yes
45209   no
45210   no

[45211 rows x 1 columns]

In [ ]:
y[y['y'] == 'yes'] = 1
y[y['y'] == 'no'] = 0
y['y'] = y['y'].astype(int)

In [ ]:
y['y'].unique()

array([0, 1])

In [ ]:
X = pd_ohe.drop('y', axis = 1)
X

,age,balance,day,duration,campaign,pdays,previous,job_admin.,job_blue-collar,job_entrepreneur,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,58.0,NaN,5.0,261.0,1.0,-1.0,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,44.0,29.0,NaN,151.0,NaN,-1.0,NaN,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,33.0,2.0,5.0,76.0,1.0,-1.0,0.0,0,0,1,...,0,0,1,0,0,0,0,0,0,0
3,47.0,NaN,5.0,92.0,1.0,-1.0,0.0,0,1,0,...,0,0,1,0,0,0,0,0,0,0
4,NaN,1.0,NaN,NaN,1.0,-1.0,0.0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51.0,825.0,17.0,977.0,NaN,NaN,NaN,0,0,0,...,0,0,0,1,0,0,0,0,0,0
45207,71.0,1729.0,17.0,456.0,NaN,-1.0,0.0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
45208,72.0,5715.0,17.0,1127.0,5.0,184.0,3.0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
45209,57.0,668.0,17.0,508.0,4.0,-1.0,0.0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
45210,37.0,2971.0,17.0,361.0,NaN,188.0,11.0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [ ]:
val_test_size = 0.3 # Proporción de la suma del test de validación y del de test.
X_train, X_tmp, Y_train, Y_tmp = train_test_split(X, y,
                                                  train_size = 0.7,
                                                  random_state = random_state,
                                                  stratify = y)

In [ ]:
X_val, X_test, Y_val, Y_test = train_test_split(X_tmp, Y_tmp,
                                                train_size = 0.5,
                                                random_state = random_state,
                                                stratify = Y_tmp)

In [ ]:
print(f'Cantidad de datos de train: {len(X_train)}')
print(f'Cantidad de datos de validación: {len(X_val)}')
print(f'Cantidad de datos de test: {len(X_test)}')

Cantidad de datos de train: 31647
Cantidad de datos de validación: 6782
Cantidad de datos de test: 6782

### **Ahora sí, a usar XGBoost**

Para usar XGBoost, creamos una instancia de la clase `XGBClassifier` y le especificamos el tipo como categórico (el parámetro `objective`). Además, podemos especificar otros parámetros típicos de XGBoost. Enlace a la documentación: https://xgboost.readthedocs.io/en/stable/parameter.html#parameters-for-tree-booster.

In [ ]:
clf_xgb = xgb.XGBClassifier(objective = 'binary:logistic',
                            seed = random_state,
                            eval_metric = 'auc')

Para entrenar el modelo, podemos llamar al método `fit` como con los otros tipos de modelo.

In [ ]:
clf_xgb.fit(X_train, Y_train, verbose = True, eval_set = [(X_val, Y_val)])

[0]	validation_0-auc:0.82470
[1]	validation_0-auc:0.84480
[2]	validation_0-auc:0.86397
[3]	validation_0-auc:0.86478
[4]	validation_0-auc:0.87343
[5]	validation_0-auc:0.88123
[6]	validation_0-auc:0.88373
[7]	validation_0-auc:0.88562
[8]	validation_0-auc:0.88861
[9]	validation_0-auc:0.88933
[10]	validation_0-auc:0.89103
[11]	validation_0-auc:0.89199
[12]	validation_0-auc:0.89284
[13]	validation_0-auc:0.89238
[14]	validation_0-auc:0.89273
[15]	validation_0-auc:0.89371
[16]	validation_0-auc:0.89430
[17]	validation_0-auc:0.89491
[18]	validation_0-auc:0.89708
[19]	validation_0-auc:0.89729
[20]	validation_0-auc:0.89744
[21]	validation_0-auc:0.89793
[22]	validation_0-auc:0.89872
[23]	validation_0-auc:0.89881
[24]	validation_0-auc:0.89882
[25]	validation_0-auc:0.89914
[26]	validation_0-auc:0.89883
[27]	validation_0-auc:0.89891
[28]	validation_0-auc:0.89902
[29]	validation_0-auc:0.89944
[30]	validation_0-auc:0.89968
[31]	validation_0-auc:0.89960
[32]	validation_0-auc:0.89950
[33]	validation_0-auc:0.89994
[34]	validation_0-auc:0.90048
[35]	validation_0-auc:0.89997
[36]	validation_0-auc:0.89996
[37]	validation_0-auc:0.89981
[38]	validation_0-auc:0.89963
[39]	validation_0-auc:0.89974
[40]	validation_0-auc:0.89957
[41]	validation_0-auc:0.90065
[42]	validation_0-auc:0.90066
[43]	validation_0-auc:0.90021
[44]	validation_0-auc:0.90002
[45]	validation_0-auc:0.89998
[46]	validation_0-auc:0.90058
[47]	validation_0-auc:0.90079
[48]	validation_0-auc:0.90071
[49]	validation_0-auc:0.90105
[50]	validation_0-auc:0.90050
[51]	validation_0-auc:0.90050
[52]	validation_0-auc:0.90059
[53]	validation_0-auc:0.90042
[54]	validation_0-auc:0.90043
[55]	validation_0-auc:0.90043
[56]	validation_0-auc:0.90061
[57]	validation_0-auc:0.90048
[58]	validation_0-auc:0.90040
[59]	validation_0-auc:0.89996
[60]	validation_0-auc:0.89964
[61]	validation_0-auc:0.89964
[62]	validation_0-auc:0.89948
[63]	validation_0-auc:0.89965
[64]	validation_0-auc:0.90014
[65]	validation_0-auc:0.90004
[66]	validation_0-auc:0.89991
[67]	validation_0-auc:0.89987
[68]	validation_0-auc:0.89997
[69]	validation_0-auc:0.89948
[70]	validation_0-auc:0.89958
[71]	validation_0-auc:0.89940
[72]	validation_0-auc:0.89912
[73]	validation_0-auc:0.89908
[74]	validation_0-auc:0.89910
[75]	validation_0-auc:0.89918
[76]	validation_0-auc:0.89930
[77]	validation_0-auc:0.89905
[78]	validation_0-auc:0.89896
[79]	validation_0-auc:0.89886
[80]	validation_0-auc:0.89906
[81]	validation_0-auc:0.89890
[82]	validation_0-auc:0.89884
[83]	validation_0-auc:0.89894
[84]	validation_0-auc:0.89887
[85]	validation_0-auc:0.89848
[86]	validation_0-auc:0.89849
[87]	validation_0-auc:0.89834
[88]	validation_0-auc:0.89836
[89]	validation_0-auc:0.89835
[90]	validation_0-auc:0.89835
[91]	validation_0-auc:0.89828
[92]	validation_0-auc:0.89819
[93]	validation_0-auc:0.89802
[94]	validation_0-auc:0.89798
[95]	validation_0-auc:0.89785
[96]	validation_0-auc:0.89777
[97]	validation_0-auc:0.89786
[98]	validation_0-auc:0.89764
[99]	validation_0-auc:0.89745

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

### **Búsqueda de hiperparámetros**

No queremos buscar hiperparámetros con cross-validation, porque tardaría mucho. Hacemos *random search* manualmente con la clase `ParameterSampler`. Aclaración: también existe la clase `ParameterGrid` por si quisiéramos hacer lo mismo con *grid search*. Definimos los posibles valores:

In [ ]:
from scipy.stats import uniform
params = {'max_depth': list(range(1, 40)),
          'learning_rate': uniform(scale = 0.2),
          'gamma': uniform(scale = 2),
          'reg_lambda': uniform(scale = 5),        # Parámetro de regularización.
          'subsample': uniform(0.5, 0.5),          # Entre 0.5 y 1.
          'min_child_weight': uniform(scale = 5),
          'colsample_bytree': uniform(0.75, 0.25), # Entre 0.75 y 1.
          'n_estimators': list(range(1, 1000))
         }

Recordemos que podemos ver las definiciones de los hiperparámetros acá: https://xgboost.readthedocs.io/en/stable/parameter.html.

In [ ]:
start = time.time()
best_score = 0
best_estimator = None
iterations = 100
for g in ParameterSampler(params, n_iter = iterations, random_state = random_state):
    clf_xgb = xgb.XGBClassifier(objective = 'binary:logistic', seed = random_state, eval_metric = 'auc', **g)
    clf_xgb.fit(X_train, Y_train, eval_set = [(X_val, Y_val)], verbose = False)

    y_pred = clf_xgb.predict_proba(X_val)[:, 1] # Obtenemos la probabilidad de una de las clases (cualquiera).
    auc_roc = sklearn.metrics.roc_auc_score(Y_val, y_pred)
    # Guardamos si es mejor.
    if auc_roc > best_score:
        print(f'Mejor valor de ROC-AUC encontrado: {auc_roc}')
        best_score = auc_roc
        best_grid = g
        best_estimator = clf_xgb

end = time.time()
print('ROC-AUC: %0.5f' % best_score)
print('Grilla:', best_grid)
print(f'Tiempo transcurrido: {str(end - start)} segundos')
print(f'Tiempo de entrenamiento por iteración: {str(round((end - start) / iterations, 2))} segundos')

Mejor valor de ROC-AUC encontrado: 0.8871468798217762
Mejor valor de ROC-AUC encontrado: 0.8966518259020139
Mejor valor de ROC-AUC encontrado: 0.901884162952269
Mejor valor de ROC-AUC encontrado: 0.9035085283917962
ROC-AUC: 0.90351
Grilla: {'colsample_bytree': 0.7626921327598493, 'gamma': 1.7732342979013198, 'learning_rate': 0.005523354374740941, 'max_depth': 34, 'min_child_weight': 0.469909699204345, 'n_estimators': 727, 'reg_lambda': 3.360130676475997, 'subsample': 0.664076333737366}
Tiempo transcurrido: 2191.9723739624023 segundos
Tiempo de entrenamiento por iteración: 21.92 segundos

¿Cuánto tardaríamos en hacer un grid search con la misma escala?

Si sólo tuviéramos 5 opciones fijas en cada parámetro, teniendo 7 parámetros, serían 546.875 multiplicado por el tiempo que dure cada iteración. Si cada iteración dura 1 segundo... esto es (sin usar paralelismo) ¡6 días!

In [ ]:
best_grid = {'colsample_bytree': 0.7626921327598493,
             'gamma': 1.7732342979013198,
             'learning_rate': 0.005523354374740941,
             'max_depth': 34,
             'min_child_weight': 0.469909699204345,
             'n_estimators': 727,
             'reg_lambda': 3.360130676475997,
             'subsample': 0.664076333737366
            }
# Aclaración: acá está "hardcodeado", pero se puede hacer mejor, accediendo a los valores de `best_grid`.

best_estimator = xgb.XGBClassifier(objective = 'binary:logistic',
                                   seed = random_state,
                                   eval_metric = 'auc',
                                   **best_grid)

best_estimator.fit(X_train, Y_train, verbose = True,  eval_set = [(X_val, Y_val)])

# roc_auc_score requiere un array 1D; da lo mismo qué dimensión le pasemos: 90 o 1.
y_pred = best_estimator.predict_proba(X_val)[:, 1]
auc_roc = sklearn.metrics.roc_auc_score(Y_val, y_pred)
print('AUC-ROC validación: %0.5f' % auc_roc)

[0]	validation_0-auc:0.84266
[1]	validation_0-auc:0.85949
[2]	validation_0-auc:0.86934
[3]	validation_0-auc:0.87212
[4]	validation_0-auc:0.87541
[5]	validation_0-auc:0.87659
[6]	validation_0-auc:0.87717
[7]	validation_0-auc:0.88326
[8]	validation_0-auc:0.88335
[9]	validation_0-auc:0.88287
[10]	validation_0-auc:0.88236
[11]	validation_0-auc:0.88298
[12]	validation_0-auc:0.88353
[13]	validation_0-auc:0.88361
[14]	validation_0-auc:0.88399
[15]	validation_0-auc:0.88351
[16]	validation_0-auc:0.88380
[17]	validation_0-auc:0.88381
[18]	validation_0-auc:0.88371
[19]	validation_0-auc:0.88446
[20]	validation_0-auc:0.88594
[21]	validation_0-auc:0.88642
[22]	validation_0-auc:0.88842
[23]	validation_0-auc:0.88892
[24]	validation_0-auc:0.88930
[25]	validation_0-auc:0.88911
[26]	validation_0-auc:0.88921
[27]	validation_0-auc:0.88913
[28]	validation_0-auc:0.88956
[29]	validation_0-auc:0.88969
[30]	validation_0-auc:0.88983
[31]	validation_0-auc:0.88984
[32]	validation_0-auc:0.88991
[33]	validation_0-auc:0.88969
[34]	validation_0-auc:0.88949
[35]	validation_0-auc:0.89059
[36]	validation_0-auc:0.89095
[37]	validation_0-auc:0.89127
[38]	validation_0-auc:0.89127
[39]	validation_0-auc:0.89125
[40]	validation_0-auc:0.89109
[41]	validation_0-auc:0.89119
[42]	validation_0-auc:0.89113
[43]	validation_0-auc:0.89135
[44]	validation_0-auc:0.89113
[45]	validation_0-auc:0.89090
[46]	validation_0-auc:0.89087
[47]	validation_0-auc:0.89098
[48]	validation_0-auc:0.89111
[49]	validation_0-auc:0.89102
[50]	validation_0-auc:0.89091
[51]	validation_0-auc:0.89092
[52]	validation_0-auc:0.89118
[53]	validation_0-auc:0.89117
[54]	validation_0-auc:0.89133
[55]	validation_0-auc:0.89116
[56]	validation_0-auc:0.89089
[57]	validation_0-auc:0.89071
[58]	validation_0-auc:0.89070
[59]	validation_0-auc:0.89075
[60]	validation_0-auc:0.89074
[61]	validation_0-auc:0.89098
[62]	validation_0-auc:0.89109
[63]	validation_0-auc:0.89090
[64]	validation_0-auc:0.89098
[65]	validation_0-auc:0.89122
[66]	validation_0-auc:0.89112
[67]	validation_0-auc:0.89117
[68]	validation_0-auc:0.89115
[69]	validation_0-auc:0.89144
[70]	validation_0-auc:0.89148
[71]	validation_0-auc:0.89146
[72]	validation_0-auc:0.89157
[73]	validation_0-auc:0.89177
[74]	validation_0-auc:0.89167
[75]	validation_0-auc:0.89186
[76]	validation_0-auc:0.89189
[77]	validation_0-auc:0.89201
[78]	validation_0-auc:0.89234
[79]	validation_0-auc:0.89246
[80]	validation_0-auc:0.89250
[81]	validation_0-auc:0.89264
[82]	validation_0-auc:0.89265
[83]	validation_0-auc:0.89267
[84]	validation_0-auc:0.89273
[85]	validation_0-auc:0.89273
[86]	validation_0-auc:0.89272
[87]	validation_0-auc:0.89263
[88]	validation_0-auc:0.89246
[89]	validation_0-auc:0.89257
[90]	validation_0-auc:0.89257
[91]	validation_0-auc:0.89258
[92]	validation_0-auc:0.89253
[93]	validation_0-auc:0.89254
[94]	validation_0-auc:0.89245
[95]	validation_0-auc:0.89247
[96]	validation_0-auc:0.89254
[97]	validation_0-auc:0.89275
[98]	validation_0-auc:0.89286
[99]	validation_0-auc:0.89288
[100]	validation_0-auc:0.89313
[101]	validation_0-auc:0.89333
[102]	validation_0-auc:0.89333
[103]	validation_0-auc:0.89332
[104]	validation_0-auc:0.89338
[105]	validation_0-auc:0.89351
[106]	validation_0-auc:0.89351
[107]	validation_0-auc:0.89343
[108]	validation_0-auc:0.89345
[109]	validation_0-auc:0.89343
[110]	validation_0-auc:0.89348
[111]	validation_0-auc:0.89362
[112]	validation_0-auc:0.89358
[113]	validation_0-auc:0.89345
[114]	validation_0-auc:0.89349
[115]	validation_0-auc:0.89336
[116]	validation_0-auc:0.89334
[117]	validation_0-auc:0.89358
[118]	validation_0-auc:0.89363
[119]	validation_0-auc:0.89364
[120]	validation_0-auc:0.89370
[121]	validation_0-auc:0.89370
[122]	validation_0-auc:0.89365
[123]	validation_0-auc:0.89380
[124]	validation_0-auc:0.89374
[125]	validation_0-auc:0.89373
[126]	validation_0-auc:0.89370
[127]	validation_0-auc:0.89376
[128]	validation_0-auc:0.89370
[129]	validation_0-auc:0.89366
[130]	validation_0-auc:0.89376
[131]	validation_0-auc:0.89390
[132]	validation_0-auc:0.89392
[133]	validation_0-auc:0.89398
[134]	validation_0-auc:0.89397
[135]	validation_0-auc:0.89399
[136]	validation_0-auc:0.89408
[137]	validation_0-auc:0.89424
[138]	validation_0-auc:0.89428
[139]	validation_0-auc:0.89427
[140]	validation_0-auc:0.89422
[141]	validation_0-auc:0.89418
[142]	validation_0-auc:0.89412
[143]	validation_0-auc:0.89418
[144]	validation_0-auc:0.89422
[145]	validation_0-auc:0.89425
[146]	validation_0-auc:0.89435
[147]	validation_0-auc:0.89440
[148]	validation_0-auc:0.89447
[149]	validation_0-auc:0.89448
[150]	validation_0-auc:0.89454
[151]	validation_0-auc:0.89465
[152]	validation_0-auc:0.89462
[153]	validation_0-auc:0.89463
[154]	validation_0-auc:0.89475
[155]	validation_0-auc:0.89476
[156]	validation_0-auc:0.89479
[157]	validation_0-auc:0.89487
[158]	validation_0-auc:0.89488
[159]	validation_0-auc:0.89487
[160]	validation_0-auc:0.89486
[161]	validation_0-auc:0.89485
[162]	validation_0-auc:0.89490
[163]	validation_0-auc:0.89504
[164]	validation_0-auc:0.89500
[165]	validation_0-auc:0.89502
[166]	validation_0-auc:0.89506
[167]	validation_0-auc:0.89515
[168]	validation_0-auc:0.89520
[169]	validation_0-auc:0.89520
[170]	validation_0-auc:0.89527
[171]	validation_0-auc:0.89541
[172]	validation_0-auc:0.89546
[173]	validation_0-auc:0.89555
[174]	validation_0-auc:0.89559
[175]	validation_0-auc:0.89558
[176]	validation_0-auc:0.89566
[177]	validation_0-auc:0.89568
[178]	validation_0-auc:0.89562
[179]	validation_0-auc:0.89564
[180]	validation_0-auc:0.89569
[181]	validation_0-auc:0.89575
[182]	validation_0-auc:0.89573
[183]	validation_0-auc:0.89577
[184]	validation_0-auc:0.89584
[185]	validation_0-auc:0.89588
[186]	validation_0-auc:0.89597
[187]	validation_0-auc:0.89602
[188]	validation_0-auc:0.89608
[189]	validation_0-auc:0.89605
[190]	validation_0-auc:0.89609
[191]	validation_0-auc:0.89614
[192]	validation_0-auc:0.89618
[193]	validation_0-auc:0.89626
[194]	validation_0-auc:0.89640
[195]	validation_0-auc:0.89640
[196]	validation_0-auc:0.89638
[197]	validation_0-auc:0.89641
[198]	validation_0-auc:0.89639
[199]	validation_0-auc:0.89638
[200]	validation_0-auc:0.89636
[201]	validation_0-auc:0.89638
[202]	validation_0-auc:0.89647
[203]	validation_0-auc:0.89652
[204]	validation_0-auc:0.89661
[205]	validation_0-auc:0.89665
[206]	validation_0-auc:0.89669
[207]	validation_0-auc:0.89673
[208]	validation_0-auc:0.89671
[209]	validation_0-auc:0.89684
[210]	validation_0-auc:0.89693
[211]	validation_0-auc:0.89697
[212]	validation_0-auc:0.89699
[213]	validation_0-auc:0.89702
[214]	validation_0-auc:0.89703
[215]	validation_0-auc:0.89707
[216]	validation_0-auc:0.89711
[217]	validation_0-auc:0.89706
[218]	validation_0-auc:0.89706
[219]	validation_0-auc:0.89706
[220]	validation_0-auc:0.89699
[221]	validation_0-auc:0.89700
[222]	validation_0-auc:0.89703
[223]	validation_0-auc:0.89709
[224]	validation_0-auc:0.89710
[225]	validation_0-auc:0.89712
[226]	validation_0-auc:0.89725
[227]	validation_0-auc:0.89727
[228]	validation_0-auc:0.89733
[229]	validation_0-auc:0.89738
[230]	validation_0-auc:0.89742
[231]	validation_0-auc:0.89741
[232]	validation_0-auc:0.89743
[233]	validation_0-auc:0.89748
[234]	validation_0-auc:0.89752
[235]	validation_0-auc:0.89757
[236]	validation_0-auc:0.89758
[237]	validation_0-auc:0.89764
[238]	validation_0-auc:0.89763
[239]	validation_0-auc:0.89761
[240]	validation_0-auc:0.89759
[241]	validation_0-auc:0.89763
[242]	validation_0-auc:0.89768
[243]	validation_0-auc:0.89772
[244]	validation_0-auc:0.89783
[245]	validation_0-auc:0.89787
[246]	validation_0-auc:0.89792
[247]	validation_0-auc:0.89798
[248]	validation_0-auc:0.89804
[249]	validation_0-auc:0.89804
[250]	validation_0-auc:0.89807
[251]	validation_0-auc:0.89815
[252]	validation_0-auc:0.89813
[253]	validation_0-auc:0.89811
[254]	validation_0-auc:0.89813
[255]	validation_0-auc:0.89813
[256]	validation_0-auc:0.89808
[257]	validation_0-auc:0.89815
[258]	validation_0-auc:0.89818
[259]	validation_0-auc:0.89821
[260]	validation_0-auc:0.89823
[261]	validation_0-auc:0.89830
[262]	validation_0-auc:0.89840
[263]	validation_0-auc:0.89839
[264]	validation_0-auc:0.89841
[265]	validation_0-auc:0.89836
[266]	validation_0-auc:0.89840
[267]	validation_0-auc:0.89836
[268]	validation_0-auc:0.89837
[269]	validation_0-auc:0.89839
[270]	validation_0-auc:0.89843
[271]	validation_0-auc:0.89842
[272]	validation_0-auc:0.89842
[273]	validation_0-auc:0.89851
[274]	validation_0-auc:0.89858
[275]	validation_0-auc:0.89860
[276]	validation_0-auc:0.89865
[277]	validation_0-auc:0.89875
[278]	validation_0-auc:0.89874
[279]	validation_0-auc:0.89878
[280]	validation_0-auc:0.89877
[281]	validation_0-auc:0.89874
[282]	validation_0-auc:0.89868
[283]	validation_0-auc:0.89873
[284]	validation_0-auc:0.89876
[285]	validation_0-auc:0.89881
[286]	validation_0-auc:0.89881
[287]	validation_0-auc:0.89884
[288]	validation_0-auc:0.89890
[289]	validation_0-auc:0.89889
[290]	validation_0-auc:0.89891
[291]	validation_0-auc:0.89895
[292]	validation_0-auc:0.89898
[293]	validation_0-auc:0.89894
[294]	validation_0-auc:0.89898
[295]	validation_0-auc:0.89901
[296]	validation_0-auc:0.89901
[297]	validation_0-auc:0.89906
[298]	validation_0-auc:0.89910
[299]	validation_0-auc:0.89912
[300]	validation_0-auc:0.89914
[301]	validation_0-auc:0.89910
[302]	validation_0-auc:0.89919
[303]	validation_0-auc:0.89922
[304]	validation_0-auc:0.89925
[305]	validation_0-auc:0.89924
[306]	validation_0-auc:0.89923
[307]	validation_0-auc:0.89923
[308]	validation_0-auc:0.89926
[309]	validation_0-auc:0.89933
[310]	validation_0-auc:0.89934
[311]	validation_0-auc:0.89938
[312]	validation_0-auc:0.89939
[313]	validation_0-auc:0.89934
[314]	validation_0-auc:0.89935
[315]	validation_0-auc:0.89947
[316]	validation_0-auc:0.89948
[317]	validation_0-auc:0.89952
[318]	validation_0-auc:0.89952
[319]	validation_0-auc:0.89953
[320]	validation_0-auc:0.89962
[321]	validation_0-auc:0.89963
[322]	validation_0-auc:0.89968
[323]	validation_0-auc:0.89970
[324]	validation_0-auc:0.89972
[325]	validation_0-auc:0.89972
[326]	validation_0-auc:0.89978
[327]	validation_0-auc:0.89983
[328]	validation_0-auc:0.89988
[329]	validation_0-auc:0.89996
[330]	validation_0-auc:0.89993
[331]	validation_0-auc:0.89991
[332]	validation_0-auc:0.89994
[333]	validation_0-auc:0.89995
[334]	validation_0-auc:0.89996
[335]	validation_0-auc:0.89998
[336]	validation_0-auc:0.89995
[337]	validation_0-auc:0.90000
[338]	validation_0-auc:0.90007
[339]	validation_0-auc:0.90009
[340]	validation_0-auc:0.90010
[341]	validation_0-auc:0.90011
[342]	validation_0-auc:0.90015
[343]	validation_0-auc:0.90018
[344]	validation_0-auc:0.90020
[345]	validation_0-auc:0.90021
[346]	validation_0-auc:0.90020
[347]	validation_0-auc:0.90020
[348]	validation_0-auc:0.90022
[349]	validation_0-auc:0.90029
[350]	validation_0-auc:0.90027
[351]	validation_0-auc:0.90031
[352]	validation_0-auc:0.90029
[353]	validation_0-auc:0.90029
[354]	validation_0-auc:0.90033
[355]	validation_0-auc:0.90033
[356]	validation_0-auc:0.90032
[357]	validation_0-auc:0.90036
[358]	validation_0-auc:0.90037
[359]	validation_0-auc:0.90036
[360]	validation_0-auc:0.90036
[361]	validation_0-auc:0.90036
[362]	validation_0-auc:0.90042
[363]	validation_0-auc:0.90046
[364]	validation_0-auc:0.90049
[365]	validation_0-auc:0.90050
[366]	validation_0-auc:0.90049
[367]	validation_0-auc:0.90056
[368]	validation_0-auc:0.90060
[369]	validation_0-auc:0.90060
[370]	validation_0-auc:0.90063
[371]	validation_0-auc:0.90067
[372]	validation_0-auc:0.90069
[373]	validation_0-auc:0.90067
[374]	validation_0-auc:0.90068
[375]	validation_0-auc:0.90070
[376]	validation_0-auc:0.90069
[377]	validation_0-auc:0.90073
[378]	validation_0-auc:0.90077
[379]	validation_0-auc:0.90079
[380]	validation_0-auc:0.90080
[381]	validation_0-auc:0.90081
[382]	validation_0-auc:0.90085
[383]	validation_0-auc:0.90086
[384]	validation_0-auc:0.90087
[385]	validation_0-auc:0.90087
[386]	validation_0-auc:0.90085
[387]	validation_0-auc:0.90086
[388]	validation_0-auc:0.90089
[389]	validation_0-auc:0.90091
[390]	validation_0-auc:0.90095
[391]	validation_0-auc:0.90097
[392]	validation_0-auc:0.90099
[393]	validation_0-auc:0.90099
[394]	validation_0-auc:0.90099
[395]	validation_0-auc:0.90102
[396]	validation_0-auc:0.90102
[397]	validation_0-auc:0.90103
[398]	validation_0-auc:0.90104
[399]	validation_0-auc:0.90099
[400]	validation_0-auc:0.90102
[401]	validation_0-auc:0.90100
[402]	validation_0-auc:0.90105
[403]	validation_0-auc:0.90104
[404]	validation_0-auc:0.90104
[405]	validation_0-auc:0.90112
[406]	validation_0-auc:0.90111
[407]	validation_0-auc:0.90118
[408]	validation_0-auc:0.90117
[409]	validation_0-auc:0.90119
[410]	validation_0-auc:0.90123
[411]	validation_0-auc:0.90120
[412]	validation_0-auc:0.90122
[413]	validation_0-auc:0.90127
[414]	validation_0-auc:0.90127
[415]	validation_0-auc:0.90128
[416]	validation_0-auc:0.90127
[417]	validation_0-auc:0.90129
[418]	validation_0-auc:0.90130
[419]	validation_0-auc:0.90131
[420]	validation_0-auc:0.90132
[421]	validation_0-auc:0.90129
[422]	validation_0-auc:0.90128
[423]	validation_0-auc:0.90131
[424]	validation_0-auc:0.90132
[425]	validation_0-auc:0.90133
[426]	validation_0-auc:0.90129
[427]	validation_0-auc:0.90127
[428]	validation_0-auc:0.90124
[429]	validation_0-auc:0.90126
[430]	validation_0-auc:0.90130
[431]	validation_0-auc:0.90131
[432]	validation_0-auc:0.90134
[433]	validation_0-auc:0.90129
[434]	validation_0-auc:0.90133
[435]	validation_0-auc:0.90133
[436]	validation_0-auc:0.90141
[437]	validation_0-auc:0.90143
[438]	validation_0-auc:0.90148
[439]	validation_0-auc:0.90153
[440]	validation_0-auc:0.90155
[441]	validation_0-auc:0.90155
[442]	validation_0-auc:0.90154
[443]	validation_0-auc:0.90154
[444]	validation_0-auc:0.90161
[445]	validation_0-auc:0.90161
[446]	validation_0-auc:0.90166
[447]	validation_0-auc:0.90167
[448]	validation_0-auc:0.90165
[449]	validation_0-auc:0.90166
[450]	validation_0-auc:0.90168
[451]	validation_0-auc:0.90169
[452]	validation_0-auc:0.90168
[453]	validation_0-auc:0.90167
[454]	validation_0-auc:0.90168
[455]	validation_0-auc:0.90168
[456]	validation_0-auc:0.90169
[457]	validation_0-auc:0.90172
[458]	validation_0-auc:0.90174
[459]	validation_0-auc:0.90178
[460]	validation_0-auc:0.90181
[461]	validation_0-auc:0.90183
[462]	validation_0-auc:0.90186
[463]	validation_0-auc:0.90189
[464]	validation_0-auc:0.90188
[465]	validation_0-auc:0.90183
[466]	validation_0-auc:0.90184
[467]	validation_0-auc:0.90183
[468]	validation_0-auc:0.90186
[469]	validation_0-auc:0.90190
[470]	validation_0-auc:0.90192
[471]	validation_0-auc:0.90193
[472]	validation_0-auc:0.90199
[473]	validation_0-auc:0.90197
[474]	validation_0-auc:0.90196
[475]	validation_0-auc:0.90197
[476]	validation_0-auc:0.90197
[477]	validation_0-auc:0.90200
[478]	validation_0-auc:0.90201
[479]	validation_0-auc:0.90203
[480]	validation_0-auc:0.90205
[481]	validation_0-auc:0.90207
[482]	validation_0-auc:0.90208
[483]	validation_0-auc:0.90211
[484]	validation_0-auc:0.90217
[485]	validation_0-auc:0.90221
[486]	validation_0-auc:0.90225
[487]	validation_0-auc:0.90222
[488]	validation_0-auc:0.90224
[489]	validation_0-auc:0.90226
[490]	validation_0-auc:0.90229
[491]	validation_0-auc:0.90225
[492]	validation_0-auc:0.90227
[493]	validation_0-auc:0.90230
[494]	validation_0-auc:0.90231
[495]	validation_0-auc:0.90236
[496]	validation_0-auc:0.90237
[497]	validation_0-auc:0.90236
[498]	validation_0-auc:0.90235
[499]	validation_0-auc:0.90239
[500]	validation_0-auc:0.90235
[501]	validation_0-auc:0.90235
[502]	validation_0-auc:0.90236
[503]	validation_0-auc:0.90238
[504]	validation_0-auc:0.90239
[505]	validation_0-auc:0.90241
[506]	validation_0-auc:0.90243
[507]	validation_0-auc:0.90245
[508]	validation_0-auc:0.90247
[509]	validation_0-auc:0.90247
[510]	validation_0-auc:0.90251
[511]	validation_0-auc:0.90252
[512]	validation_0-auc:0.90252
[513]	validation_0-auc:0.90250
[514]	validation_0-auc:0.90250
[515]	validation_0-auc:0.90248
[516]	validation_0-auc:0.90247
[517]	validation_0-auc:0.90245
[518]	validation_0-auc:0.90242
[519]	validation_0-auc:0.90245
[520]	validation_0-auc:0.90246
[521]	validation_0-auc:0.90248
[522]	validation_0-auc:0.90250
[523]	validation_0-auc:0.90247
[524]	validation_0-auc:0.90248
[525]	validation_0-auc:0.90247
[526]	validation_0-auc:0.90246
[527]	validation_0-auc:0.90252
[528]	validation_0-auc:0.90252
[529]	validation_0-auc:0.90254
[530]	validation_0-auc:0.90255
[531]	validation_0-auc:0.90256
[532]	validation_0-auc:0.90258
[533]	validation_0-auc:0.90257
[534]	validation_0-auc:0.90260
[535]	validation_0-auc:0.90259
[536]	validation_0-auc:0.90260
[537]	validation_0-auc:0.90262
[538]	validation_0-auc:0.90263
[539]	validation_0-auc:0.90260
[540]	validation_0-auc:0.90263
[541]	validation_0-auc:0.90265
[542]	validation_0-auc:0.90263
[543]	validation_0-auc:0.90264
[544]	validation_0-auc:0.90263
[545]	validation_0-auc:0.90264
[546]	validation_0-auc:0.90266
[547]	validation_0-auc:0.90266
[548]	validation_0-auc:0.90270
[549]	validation_0-auc:0.90273
[550]	validation_0-auc:0.90274
[551]	validation_0-auc:0.90275
[552]	validation_0-auc:0.90277
[553]	validation_0-auc:0.90277
[554]	validation_0-auc:0.90276
[555]	validation_0-auc:0.90280
[556]	validation_0-auc:0.90277
[557]	validation_0-auc:0.90281
[558]	validation_0-auc:0.90281
[559]	validation_0-auc:0.90281
[560]	validation_0-auc:0.90283
[561]	validation_0-auc:0.90281
[562]	validation_0-auc:0.90290
[563]	validation_0-auc:0.90295
[564]	validation_0-auc:0.90295
[565]	validation_0-auc:0.90295
[566]	validation_0-auc:0.90299
[567]	validation_0-auc:0.90297
[568]	validation_0-auc:0.90294
[569]	validation_0-auc:0.90294
[570]	validation_0-auc:0.90296
[571]	validation_0-auc:0.90293
[572]	validation_0-auc:0.90295
[573]	validation_0-auc:0.90296
[574]	validation_0-auc:0.90295
[575]	validation_0-auc:0.90295
[576]	validation_0-auc:0.90298
[577]	validation_0-auc:0.90299
[578]	validation_0-auc:0.90298
[579]	validation_0-auc:0.90297
[580]	validation_0-auc:0.90297
[581]	validation_0-auc:0.90297
[582]	validation_0-auc:0.90298
[583]	validation_0-auc:0.90297
[584]	validation_0-auc:0.90299
[585]	validation_0-auc:0.90299
[586]	validation_0-auc:0.90302
[587]	validation_0-auc:0.90306
[588]	validation_0-auc:0.90303
[589]	validation_0-auc:0.90305
[590]	validation_0-auc:0.90306
[591]	validation_0-auc:0.90307
[592]	validation_0-auc:0.90310
[593]	validation_0-auc:0.90311
[594]	validation_0-auc:0.90315
[595]	validation_0-auc:0.90315
[596]	validation_0-auc:0.90315
[597]	validation_0-auc:0.90315
[598]	validation_0-auc:0.90317
[599]	validation_0-auc:0.90316
[600]	validation_0-auc:0.90315
[601]	validation_0-auc:0.90316
[602]	validation_0-auc:0.90316
[603]	validation_0-auc:0.90315
[604]	validation_0-auc:0.90313
[605]	validation_0-auc:0.90314
[606]	validation_0-auc:0.90313
[607]	validation_0-auc:0.90309
[608]	validation_0-auc:0.90313
[609]	validation_0-auc:0.90311
[610]	validation_0-auc:0.90310
[611]	validation_0-auc:0.90310
[612]	validation_0-auc:0.90311
[613]	validation_0-auc:0.90313
[614]	validation_0-auc:0.90313
[615]	validation_0-auc:0.90314
[616]	validation_0-auc:0.90313
[617]	validation_0-auc:0.90314
[618]	validation_0-auc:0.90312
[619]	validation_0-auc:0.90312
[620]	validation_0-auc:0.90315
[621]	validation_0-auc:0.90316
[622]	validation_0-auc:0.90316
[623]	validation_0-auc:0.90317
[624]	validation_0-auc:0.90318
[625]	validation_0-auc:0.90320
[626]	validation_0-auc:0.90321
[627]	validation_0-auc:0.90320
[628]	validation_0-auc:0.90324
[629]	validation_0-auc:0.90325
[630]	validation_0-auc:0.90324
[631]	validation_0-auc:0.90325
[632]	validation_0-auc:0.90325
[633]	validation_0-auc:0.90327
[634]	validation_0-auc:0.90326
[635]	validation_0-auc:0.90328
[636]	validation_0-auc:0.90329
[637]	validation_0-auc:0.90330
[638]	validation_0-auc:0.90328
[639]	validation_0-auc:0.90325
[640]	validation_0-auc:0.90328
[641]	validation_0-auc:0.90327
[642]	validation_0-auc:0.90326
[643]	validation_0-auc:0.90323
[644]	validation_0-auc:0.90324
[645]	validation_0-auc:0.90326
[646]	validation_0-auc:0.90326
[647]	validation_0-auc:0.90326

Una vez entrenado, podemos observar atributos de cada campo como, por ejemplo, el `cover`:

In [ ]:
bst = best_estimator.get_booster()
for importance_type in ('weight', 'gain', 'cover', 'total_gain', 'total_cover'):
    print('%s: ' % importance_type, bst.get_score(importance_type = importance_type))
    print('--------------')

weight:  {'age': 20313.0, 'balance': 25582.0, 'day': 20270.0, 'duration': 23876.0, 'campaign': 9372.0, 'pdays': 10966.0, 'previous': 6781.0, 'job_admin.': 1395.0, 'job_blue-collar': 1331.0, 'job_entrepreneur': 554.0, 'job_housemaid': 468.0, 'job_management': 1816.0, 'job_retired': 895.0, 'job_self-employed': 649.0, 'job_services': 746.0, 'job_student': 1009.0, 'job_technician': 1667.0, 'job_unemployed': 654.0, 'job_unknown': 62.0, 'marital_divorced': 1348.0, 'marital_married': 1730.0, 'marital_single': 1905.0, 'education_primary': 945.0, 'education_secondary': 1709.0, 'education_tertiary': 2038.0, 'education_unknown': 922.0, 'default_no': 1620.0, 'default_yes': 279.0, 'housing_no': 1988.0, 'housing_yes': 1565.0, 'loan_no': 1852.0, 'loan_yes': 1068.0, 'contact_cellular': 2082.0, 'contact_telephone': 977.0, 'contact_unknown': 1233.0, 'month_apr': 1944.0, 'month_aug': 1935.0, 'month_dec': 900.0, 'month_feb': 2406.0, 'month_jan': 926.0, 'month_jul': 1418.0, 'month_jun': 1824.0, 'month_mar': 1449.0, 'month_may': 1788.0, 'month_nov': 1523.0, 'month_oct': 1995.0, 'month_sep': 1326.0, 'poutcome_failure': 1102.0, 'poutcome_other': 931.0, 'poutcome_success': 1097.0, 'poutcome_unknown': 1527.0}
--------------
gain:  {'age': 3.2664954662323, 'balance': 2.7928380966186523, 'day': 3.022719383239746, 'duration': 10.605772018432617, 'campaign': 2.740678071975708, 'pdays': 3.9060754776000977, 'previous': 3.4456627368927, 'job_admin.': 2.2584128379821777, 'job_blue-collar': 3.1164968013763428, 'job_entrepreneur': 2.0440142154693604, 'job_housemaid': 1.9815170764923096, 'job_management': 2.448700428009033, 'job_retired': 2.248957395553589, 'job_self-employed': 1.8137131929397583, 'job_services': 2.097897529602051, 'job_student': 4.278084754943848, 'job_technician': 2.340054512023926, 'job_unemployed': 1.7977700233459473, 'job_unknown': 1.2725988626480103, 'marital_divorced': 2.2589399814605713, 'marital_married': 2.548784017562866, 'marital_single': 2.754692792892456, 'education_primary': 2.331138849258423, 'education_secondary': 2.439039468765259, 'education_tertiary': 2.617690086364746, 'education_unknown': 2.149238348007202, 'default_no': 2.410853147506714, 'default_yes': 1.9319267272949219, 'housing_no': 6.717798233032227, 'housing_yes': 5.999749660491943, 'loan_no': 2.95190691947937, 'loan_yes': 3.7294561862945557, 'contact_cellular': 4.504169464111328, 'contact_telephone': 2.249438762664795, 'contact_unknown': 18.871177673339844, 'month_apr': 4.727335453033447, 'month_aug': 3.153804063796997, 'month_dec': 3.8490712642669678, 'month_feb': 3.1668169498443604, 'month_jan': 3.0301644802093506, 'month_jul': 3.4231390953063965, 'month_jun': 4.266534328460693, 'month_mar': 9.805371284484863, 'month_may': 3.951615333557129, 'month_nov': 2.936836004257202, 'month_oct': 6.850875377655029, 'month_sep': 6.10273551940918, 'poutcome_failure': 4.084259510040283, 'poutcome_other': 2.696871280670166, 'poutcome_success': 55.1828498840332, 'poutcome_unknown': 2.826709508895874}
--------------
cover:  {'age': 114.6599349975586, 'balance': 65.48277282714844, 'day': 58.75162124633789, 'duration': 193.81100463867188, 'campaign': 66.26156616210938, 'pdays': 106.2444839477539, 'previous': 113.01422882080078, 'job_admin.': 54.472503662109375, 'job_blue-collar': 115.81991577148438, 'job_entrepreneur': 68.06199645996094, 'job_housemaid': 89.13887786865234, 'job_management': 52.01087188720703, 'job_retired': 68.90653228759766, 'job_self-employed': 56.149532318115234, 'job_services': 44.75181579589844, 'job_student': 334.53759765625, 'job_technician': 40.05204391479492, 'job_unemployed': 62.69914245605469, 'job_unknown': 138.98049926757812, 'marital_divorced': 54.665706634521484, 'marital_married': 51.6923713684082, 'marital_single': 96.1667709350586, 'education_primary': 51.05366897583008, 'education_secondary': 28.27823829650879, 'education_tertiary': 60.31739807128906, 'education_unknown': 86.14749908447266, 'default_no': 33.01185989379883, 'default_yes': 91.93698120117188, 'housing_no': 228.46270751953125, 'housing_yes': 275.2687683105469, 'loan_no': 68.9944839477539, 'loan_yes': 143.13059997558594, 'contact_cellular': 139.27835083007812, 'contact_telephone': 50.785987854003906, 'contact_unknown': 825.3280639648438, 'month_apr': 238.1750030517578, 'month_aug': 87.65547943115234, 'month_dec': 402.7683410644531, 'month_feb': 172.69479370117188, 'month_jan': 125.93927764892578, 'month_jul': 115.5142593383789, 'month_jun': 213.18905639648438, 'month_mar': 630.7988891601562, 'month_may': 115.5521011352539, 'month_nov': 92.12056732177734, 'month_oct': 455.99322509765625, 'month_sep': 505.13580322265625, 'poutcome_failure': 74.96260070800781, 'poutcome_other': 127.93701934814453, 'poutcome_success': 1096.4150390625, 'poutcome_unknown': 52.975914001464844}
--------------
total_gain:  {'age': 66352.3203125, 'balance': 71446.3828125, 'day': 61270.5234375, 'duration': 253223.421875, 'campaign': 25685.634765625, 'pdays': 42834.0234375, 'previous': 23365.0390625, 'job_admin.': 3150.48583984375, 'job_blue-collar': 4148.05712890625, 'job_entrepreneur': 1132.3839111328125, 'job_housemaid': 927.3499755859375, 'job_management': 4446.83984375, 'job_retired': 2012.81689453125, 'job_self-employed': 1177.099853515625, 'job_services': 1565.0316162109375, 'job_student': 4316.58740234375, 'job_technician': 3900.870849609375, 'job_unemployed': 1175.7415771484375, 'job_unknown': 78.90113067626953, 'marital_divorced': 3045.051025390625, 'marital_married': 4409.396484375, 'marital_single': 5247.68994140625, 'education_primary': 2202.92626953125, 'education_secondary': 4168.318359375, 'education_tertiary': 5334.8525390625, 'education_unknown': 1981.5977783203125, 'default_no': 3905.582275390625, 'default_yes': 539.007568359375, 'housing_no': 13354.982421875, 'housing_yes': 9389.6083984375, 'loan_no': 5466.931640625, 'loan_yes': 3983.059326171875, 'contact_cellular': 9377.6806640625, 'contact_telephone': 2197.70166015625, 'contact_unknown': 23268.162109375, 'month_apr': 9189.9404296875, 'month_aug': 6102.61083984375, 'month_dec': 3464.1640625, 'month_feb': 7619.361328125, 'month_jan': 2805.932373046875, 'month_jul': 4854.01123046875, 'month_jun': 7782.15869140625, 'month_mar': 14207.9833984375, 'month_may': 7065.48828125, 'month_nov': 4472.80126953125, 'month_oct': 13667.49609375, 'month_sep': 8092.2275390625, 'poutcome_failure': 4500.85400390625, 'poutcome_other': 2510.787109375, 'poutcome_success': 60535.5859375, 'poutcome_unknown': 4316.38525390625}
--------------
total_cover:  {'age': 2329087.25, 'balance': 1675180.25, 'day': 1190895.375, 'duration': 4627431.5, 'campaign': 621003.375, 'pdays': 1165077.0, 'previous': 766349.5, 'job_admin.': 75989.140625, 'job_blue-collar': 154156.3125, 'job_entrepreneur': 37706.34765625, 'job_housemaid': 41716.99609375, 'job_management': 94451.7421875, 'job_retired': 61671.34375, 'job_self-employed': 36441.046875, 'job_services': 33384.85546875, 'job_student': 337548.4375, 'job_technician': 66766.7578125, 'job_unemployed': 41005.23828125, 'job_unknown': 8616.791015625, 'marital_divorced': 73689.375, 'marital_married': 89427.8046875, 'marital_single': 183197.703125, 'education_primary': 48245.71875, 'education_secondary': 48327.5078125, 'education_tertiary': 122926.859375, 'education_unknown': 79427.9921875, 'default_no': 53479.21484375, 'default_yes': 25650.41796875, 'housing_no': 454183.875, 'housing_yes': 430795.625, 'loan_no': 127777.78125, 'loan_yes': 152863.484375, 'contact_cellular': 289977.53125, 'contact_telephone': 49617.91015625, 'contact_unknown': 1017629.5, 'month_apr': 463012.21875, 'month_aug': 169613.359375, 'month_dec': 362491.5, 'month_feb': 415503.6875, 'month_jan': 116619.7734375, 'month_jul': 163799.21875, 'month_jun': 388856.84375, 'month_mar': 914027.5625, 'month_may': 206607.15625, 'month_nov': 140299.625, 'month_oct': 909706.5, 'month_sep': 669810.0625, 'poutcome_failure': 82608.7890625, 'poutcome_other': 119109.3671875, 'poutcome_success': 1202767.25, 'poutcome_unknown': 80894.21875}
--------------

### **Conjunto de test**

Para finalizar, ejecutamos el modelo para el conjunto de test, para tener una mejor estimación de cómo se comportaría el modelo en un escenario de producción, con un conjunto de datos que el modelo nunca ha visto y que tampoco se ha usado para tomar decisiones.

In [ ]:
y_pred = best_estimator.predict_proba(X_test)[:, 1]
auc_roc = sklearn.metrics.roc_auc_score(Y_test, y_pred)
print('AUC-ROC test: %0.5f' % auc_roc)

AUC-ROC test: 0.89681

Efectivamente, vemos que la *performance* es ligeramente menor en el conjunto de test.